name: Build .NET MAUI App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0  # Adjust to your required .NET version

    - name: Install Android SDK
      uses: maltoze/setup-android@v1
      with:
        api-level: 33
        build-tools: 33.0.0
        components: platform-tools

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release -f:net8.0-android

    - name: Publish Android APK
      run: dotnet publish -f:net8.0-android -c Release -o output/

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: output/**/*.apk

  build-ios:
    name: Build iOS App
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0  # Adjust to your required .NET version

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app  # Use the appropriate Xcode version for your project

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release -f:net8.0-ios

    - name: Publish iOS IPA
      run: dotnet publish -f:net8.0-ios -c Release -o output/

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ios-ipa
        path: output/**/*.ipa
