name: Build iOS

on:
  workflow_dispatch:
  #push:
    #branches: [ "main" ]
    #paths-ignore:
      #- "**.md"
      #- '**/*.gitignore'
      #- '**/*.gitattributes'
      #- '**/*.yml'
      #- '**.txt'
      #- '**/*.txt'
  
  #pull_request:
    #branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    
  # These expire on a yearly basis, so check if they're still valid!
    - uses: apple-actions/import-codesign-certs@v3
      with: 
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }} 

    - uses: actions/checkout@v3
      name: Checkout repo
   
    - uses: maxim-lobanov/setup-xcode@v1
      name: Set XCode version
      with:
        xcode-version: 15.0
      
    - name: Download Provisioning Profiles
      id: provisioning
      uses: apple-actions/download-provisioning-profiles@v1
      with: 
        bundle-id: com.cyberaustin.sofagasbuddy
        profile-type: 'appstore-release'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEYID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
        
    - name: Install .NET MAUI
      run: dotnet workload install maui
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build SOFAGasBuddy.csproj -c Release -f net8.0-ios /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          ./**/*.app
