name: Build .NET MAUI App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x  # Use the latest stable .NET 8.0

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O android-tools.zip
        unzip android-tools.zip -d $HOME/android-sdk
        yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.0"

    - name: Set up environment variables
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/bin:$HOME/android-sdk/build-tools/33.0.0" >> $GITHUB_ENV

    - name: Install required workloads
      run: dotnet workload install maui-android microsoft-ios-sdk-full

    - name: Restore .NET workloads
      run: dotnet workload restore

    - name: Build the project
      run: dotnet build --configuration Release -f:net8.0-android

    - name: Publish Android APK
      run: dotnet publish -f:net8.0-android -c Release -o output/

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: output/**/*.apk

  build-ios:
    name: Build iOS App
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x  # Use the latest stable .NET 8.0

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app  # Use Xcode 15.0

    - name: Install required workloads
      run: |
        dotnet workload install maui-ios microsoft-net-runtime-ios microsoft-ios-sdk-full

    - name: Restore .NET workloads
      run: dotnet workload restore

    - name: Build the project
      run: dotnet build --configuration Release -f:net8.0-ios

    - name: Publish iOS IPA
      run: dotnet publish -f:net8.0-ios -c Release -o output/

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ios-ipa
        path: output/**/*.ipa
